services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: kanban
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d kanban"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
    depends_on: [db]

  api:
    build:
      context: ./backend
      dockerfile: ../ops/backend.Dockerfile
    env_file: ./backend/.env
    ports: ["4000:4000"]
    depends_on: [db]

  web:
    build:
      context: ./frontend
      dockerfile: ../ops/frontend.Dockerfile
    env_file: ./frontend/.env
    ports: ["5173:80"]
    depends_on: [api]

volumes:
  pgdata: {}
